### ISSUE TITLE
Setting the targets in Environment if they don't exist

### ISSUE THREAD

**Issue by mezdn** [cmps253/design-architecture#7] opened 2020-03-23 11:49 UTC
In [Lesson7.Solution2.LogConfig.CreateFromEnvironment():](https://github.com/cmps253/design-architecture/blob/master/Lesson%2007%20Dynamic%20Log%20Output/Solution%202%20Environment%20Variables/Source%20Code/MultiLogger/LogConfig.cs)
Line 24: 

> 21 string targets = Environment.GetEnvironmentVariable("targets");
> 22 if (targets == null)
> 23 {
> 24      targets = DefaultTargetsLine.ToUpper();
> 25 }

We are assigning the whole statement  `targets=fc` to targets, 
where it should only be `fc`
(as if saying _targets=targets=fc_)

**Comment by mbdeir** [comment] 2020-03-29 10:30
I am reading the whole line and then checking if it contains F, then C. The default is by design `targets=fc` so starting form line 28 `if (targets.Contains('C'))` I give it the same treatment whether it was provided by the environment or not (as a default).

Where is the problem? Please close the issue.

**Comment by mezdn** [comment] 2020-03-29 12:31
What I meant is that in line 24 you're not assigning the value `fc` to `targets`, but the value `targets=fc`, in other words, in line 25 you'll obtain the following: `targets=targets=fc`.
(Check line 69: of the the same class, to see the difference).
This will work fine for now, since the word "targets" doesn't contain any character that is meant to refer to an output destination, but it could do so in the future.

**Comment by mbdeir** [comment] 2020-03-29 12:56
Yes, that is true I am assigning targets=fc, again, as if I read it from the file or from the env var... Again, so I give it the same treatment in the rest of the code. I don't see your point.

**Closed** 2020-03-29 13:10 UTC
